version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - ./id_jenkins_rsa:/var/jenkins_home/.ssh/id_rsa
      - /var/run/docker.sock:/var/run/docker.sock
  
  agent:
    image: jenkins-agent-with-docker-cli
    build:
      context: .
    privileged: true
    user: root
    container_name: agent

volumes:
  jenkins-data:
    name: "jenkins-instance_jenkins-data"
